### ISSUE TITLE
Updating game pass icons does not work

### ISSUE THREAD

**Issue by guidojw** [blake-mealey/mantle#148] opened 2022-06-14 19:53 UTC
**Describe the bug**
When updating a game pass icon, Mantle errors with a 404 Not Found.

**To Reproduce**
1. Deploy a game pass with initial icon.
2. Change the icon file and deploy again.
3. Mantle errors with 404 Not Found.

**Expected behavior**
The icon is correctly updated.

**Environment (please complete the following information):**
 - OS: Windows
 - Mantle Version 0.11.1

**Additional context**
It looks like this is because of the usage of `POST https://publish.roblox.com/v1/game-passes/:gamePassId/icon`, which does not seem to exist (tested this with Postman).
https://github.com/blake-mealey/mantle/blob/0adfb6333ed5f0f8e96260d73cee99d09c07ef70/rbx_mantle/src/roblox_api.rs#L1536

When manually updating the game pass icon and checking the browser logs, only one request is made and this is to `https://www.roblox.com/game-pass/update`, same as in `update_game_pass`:
https://github.com/blake-mealey/mantle/blob/0adfb6333ed5f0f8e96260d73cee99d09c07ef70/rbx_mantle/src/roblox_api.rs#L1514

When the game pass icon is changed, this request is encoded as gzip and includes the new image.

**Comment by blake-mealey** [comment] 2022-06-14 22:33
You're right though. Mantle already uses that endpoint and I'm not seeing anything else, so might as well switch to that.

**Comment by blake-mealey** [comment] 2022-06-15 22:52
@guidojw this turned out to be more complex than it looks. Internally Mantle considers game passes and game pass icons to be separate resources. This lets it only update the game pass if the description (for example) changes and only updates the icon if the icon file changes. However, if you upload just an icon with that update endpoint it actually overwrites the name and description properties.

Therefore, I would need to combine the two into a single game pass resource. Unfortunately this means that whenever the developer changes the description, the icon will need to be reuploaded.

Additionally, the update endpoint does not return the new icon asset ID, so we are forced to make a second request to fetch the icon asset ID from the game pass.

Although not ideal, it's better than not working at all. I should have a patch out soon but just updating you on why this is more complex than it seems.

**Comment by blake-mealey** [comment] 2022-06-15 22:54
Also realized this would require a new state file version which is rather annoying. Before publishing this change I want to make a ticket on the devforum to see if Roblox will respond to this.

**Comment by blake-mealey** [comment] 2022-06-15 23:02
Created this ticket: https://devforum.roblox.com/t/update-game-pass-icon-web-api-no-longer-exists/1834807

**Comment by blake-mealey** [comment] 2022-06-17 01:55
Roblox has confirmed that this was intentionally removed but they missed on communicating it, and that they are intending on replacing it with an Open Cloud API.

Since Open Cloud cannot be supported by Mantle yet, I'll go ahead and implement the above change.

**Comment by blake-mealey** [comment] 2022-06-17 23:04
This is fixed in the latest release (0.11.2)

**Closed by blake-mealey** 2022-06-17 23:04 UTC
Labels: bug

**Comment by guidojw** [comment] 2022-06-17 23:08
Hi yeah, thanks for the quick response and fix!
